import{Teacher} from './teacher';
import { Student } from './student';
import { Course } from './courses';
const teacher1 = new Teacher("Teacher",1, "Mr. Smith",20,"Mirpur-12","6-Years");
const mathCourse = new Course(1, "Mathematics");
const javaCourse = new Course(4, "Java");
const computerCourse=new Course(6,"Computer Network");
//teacher1.display();
teacher1.assignCourse(mathCourse);
teacher1.assignCourse(javaCourse);
teacher1.assignCourse(computerCourse);
// const student1=new Student("Student",101,"Rose","Aladuddin","Khadiza","01792144467");
// const student2=new Student("Student",111,"Mitu","Aladuddin","Khadiza","01792144467");
// student1.display();
// student1.enrollCourse(mathCourse);
// student1.enrollCourse(javaCourse);
// student2.enrollCourse(javaCourse);